const fs = require('fs'); 
const p = 'src/pages/HubDashboard.jsx'; 
let s = fs.readFileSync(p, 'utf8'); 
s = s.replace(/t\.saludTitle/g, "t.saludTitle || 'Smart Salud'")
     .replace(/t\.saludSub/g, "t.saludSub || 'Agendamiento'")
     .replace(/t\.kioskoTitle/g, "t.kioskoTitle || 'Kiosko'")
     .replace(/t\.kioskoSub/g, "t.kioskoSub || 'Noticias'")
     .replace(/t\.airportTitle/g, "t.airportTitle || 'Aeropuerto'")
     .replace(/t\.airportSub/g, "t.airportSub || 'Vuelos en vivo'")
     .replace(/t\.visionTitle/g, "t.visionTitle || 'Visión'")
     .replace(/t\.visionSub/g, "t.visionSub || 'Reportes'")
     .replace(/t\.broadcasterTitle/g, "t.broadcasterTitle || 'Estudio VLS'")
     .replace(/t\.broadcasterSub/g, "t.broadcasterSub || 'Streaming'")
     .replace(/t\.memoryTitle/g, "t.memoryTitle || 'Memoria'")
     .replace(/t\.memorySub/g, "t.memorySub || 'Historia'")
     .replace(/t\.auditoriaTitle/g, "t.auditoriaTitle || 'Auditoría'")
     .replace(/t\.auditoriaSub/g, "t.auditoriaSub || 'Gobierno Abierto'")
     .replace(/t\.parlamentoTitle/g, "t.parlamentoTitle || 'Parlamento'")
     .replace(/t\.parlamentoSub/g, "t.parlamentoSub || 'Debate'")
     .replace(/t\.projectTitle/g, "t.projectTitle || 'Proyecto'")
     .replace(/t\.projectSub/g, "t.projectSub || 'Información'")
     .replace(/t\.cdlsTitle/g, "t.cdlsTitle || 'CDLS'")
     .replace(/t\.cdlsSub/g, "t.cdlsSub || 'Pasión Granate'")
     .replace(/t\.musicTitle/g, "t.musicTitle || 'Música'")
     .replace(/t\.musicSub/g, "t.musicSub || 'Estudio IA'")
     .replace(/t\.retroTitle/g, "t.retroTitle || 'Televisor'")
     .replace(/t\.retroSub/g, "t.retroSub || 'Canales 80s'")
     .replace(/t\.vhsTitle/g, "t.vhsTitle || 'Videoclub'")
     .replace(/t\.vhsSub/g, "t.vhsSub || 'Películas VHS'")
     .replace(/t\.faritoTitle/g, "t.faritoTitle || 'Navegador'")
     .replace(/t\.faritoSub/g, "t.faritoSub || 'Faro'")
     .replace(/t\.glosarioTitle/g, "t.glosarioTitle || 'Glosario'")
     .replace(/t\.glosarioSub/g, "t.glosarioSub || 'Términos'"); 
fs.writeFileSync(p, s);
