const fs = require('fs');
const path = 'src/pages/HubDashboard.jsx';
const content = fs.readFileSync(path, 'utf8');
const lines = content.split(/\r?\n/);

// Find the start of the section
const startIndex = lines.findIndex(l => l.includes('SMART CITIZENS PREMIUM CARD'));
// Find the end of the section (just before the C5 section)
const endIndex = lines.findIndex(l => l.includes('NUEVA SECCI'));

if (startIndex !== -1 && endIndex !== -1) {
    const cleanBlock = [
        "                        {/* SMART CITIZENS PREMIUM CARD */}",
        "                        <div style={{ maxWidth: '1400px', margin: '0 auto 2.5rem auto', width: '100%', padding: '0 2rem', boxSizing: 'border-box' }}>",
        "                             <div ",
        "                                  onClick={() => window.dispatchEvent(new CustomEvent('open-vls-reporte'))}",
        "                                  className=\"glass-panel gaudi-curves hover-lift animate-fade-in\" ",
        "                                  style={{ ",
        "                                      background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.7) 0%, rgba(2, 6, 23, 0.95) 100%)', ",
        "                                      padding: isMobile ? '1.5rem' : '2.5rem', ",
        "                                      borderRadius: '35px', ",
        "                                      cursor: 'pointer',",
        "                                      border: '1px solid rgba(16, 185, 129, 0.5)',",
        "                                      position: 'relative',",
        "                                      overflow: 'hidden',",
        "                                      display: 'flex',",
        "                                      flexDirection: 'column',",
        "                                      marginBottom: '2.5rem',",
        "                                      boxShadow: '0 25px 50px -12px rgba(16, 185, 129, 0.2)'",
        "                                  }}",
        "                             >",
        "                                 <div style={{ position: 'absolute', inset: 0, backgroundImage: 'url(\"/vls_seguridad_central.png\")', backgroundSize: 'cover', backgroundPosition: 'center', opacity: 0.35, zIndex: 0 }}></div>",
        "                                 <div style={{ position: 'relative', zIndex: 1, height: '100%', display: 'flex', flexDirection: 'column' }}>",
        "                                     <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '1.2rem' }}>",
        "                                         <div style={{ background: '#10b981', color: 'white', padding: '5px 15px', borderRadius: '10px', fontSize: '0.8rem', fontWeight: 900, letterSpacing: '1px', display: 'flex', alignItems: 'center', gap: '8px', boxShadow: '0 5px 15px rgba(16,185,129,0.5)' }}>",
        "                                             🚀 SMART CITIZENS",
        "                                         </div>",
        "                                         <div style={{ display: 'flex', gap: '8px', color: '#10b981' }}>",
        "                                             <Shield size={18} />",
        "                                         </div>",
        "                                     </div>",
        "                                     <h2 style={{ color: 'white', fontSize: isMobile ? '1.8rem' : '2.5rem', fontWeight: 900, lineHeight: 1.1, marginBottom: '1rem', fontFamily: '\"Outfit\", sans-serif' }}>REPORTE VECINAL</h2>",
        "                                     <p style={{ color: 'rgba(255,255,255,0.9)', fontSize: '1.1rem', margin: '0 0 1.5rem 0', fontWeight: 400, lineHeight: 1.4, flex: 1 }}>",
        "                                         Portal georreferenciado para reportes de baches, luminarias, playas y humedales. Tu voz construye una ciudad inteligente.",
        "                                     </p>",
        "                                     <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto' }}>",
        "                                         <button className=\"btn-vls-action-light\" style={{ background: '#10b981', color: 'white', padding: '0.8rem 2rem', fontSize: '0.9rem', border: 'none', borderRadius: '15px', fontWeight: '900' }}>CREAR REPORTE</button>",
        "                                         <span style={{ color: '#10b981', fontWeight: 'bold', fontSize: '0.8rem', letterSpacing: '2px' }}>VLS SEGURIDAD</span>",
        "                                     </div>",
        "                                 </div>",
        "                             </div>",
        "",
        "                             <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, 1fr)', gap: '2rem' }}>",
        "                                 {/* JORGE CAMPOS REPORT */}",
        "                                 <div ",
        "                                     onClick={() => {",
        "                                         const ev = new CustomEvent('open-vls-note', { detail: 'ZAJpC9o-Mok' });",
        "                                         window.dispatchEvent(ev);",
        "                                     }}",
        "                                     className=\"glass-panel gaudi-curves hover-lift animate-fade-in\" ",
        "                                     style={{ ",
        "                                         background: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)', ",
        "                                         padding: isMobile ? '1.5rem' : '2.5rem', ",
        "                                         borderRadius: '35px', ",
        "                                         cursor: 'pointer',",
        "                                         border: '1px solid rgba(59,130,246,0.4)',",
        "                                         position: 'relative',",
        "                                         overflow: 'hidden',",
        "                                         display: 'flex',",
        "                                         flexDirection: 'column',",
        "                                         boxShadow: '0 20px 40px rgba(0,0,0,0.5)'",
        "                                     }}",
        "                                 >",
        "                                     <div style={{ position: 'absolute', top: '-5%', right: '-5%', opacity: 0.08, zIndex: 0 }}>",
        "                                         <Music size={isMobile ? 150 : 200} color=\"#3b82f6\" />",
        "                                     </div>",
        "                                     <div style={{ position: 'relative', zIndex: 1, height: '100%', display: 'flex', flexDirection: 'column' }}>",
        "                                         <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>",
        "                                             <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>",
        "                                                 <span style={{ background: '#3b82f6', color: 'white', padding: '0.4rem 1.2rem', borderRadius: '50px', fontSize: '0.7rem', fontWeight: 900 }}>ARTE Y CULTURA</span>",
        "                                             </div>",
        "                                             <div style={{ display: 'flex', gap: '8px', color: '#3b82f6', opacity: 0.8 }}>",
        "                                                 <Music size={18} />",
        "                                             </div>",
        "                                         </div>",
        "                                         <h2 style={{ color: 'white', fontSize: isMobile ? '1.5rem' : '1.8rem', fontWeight: 900, lineHeight: 1.1, marginBottom: '1rem', fontFamily: '\"Outfit\", sans-serif' }}>JORGE CAMPOS</h2>",
        "                                         <p style={{ color: 'rgba(255,255,255,0.9)', fontSize: '0.95rem', margin: '0 0 1.5rem 0', fontWeight: 400, lineHeight: 1.4, flex: 1 }}>",
        "                                             La Arquitectura y el Arte de Girar: El virtuoso bajista de Congreso y Fulano reflexiona sobre el bajo como cimiento.",
        "                                         </p>",
        "                                         <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto' }}>",
        "                                             <button className=\"btn-vls-action-light\" style={{ background: '#3b82f6', color: 'white', padding: '0.6rem 1.5rem', fontSize: '0.8rem', border: 'none', borderRadius: '12px', fontWeight: '900' }}>VER SESIÓN</button>",
        "                                             <span style={{ color: '#3b82f6', fontWeight: 'bold', fontSize: '0.7rem', letterSpacing: '1px' }}>VLS MASTERCLASS</span>",
        "                                         </div>",
        "                                     </div>",
        "                                 </div>",
        "",
        "                                 {/* IGLESIAS DE PIEDRA REPORT */}",
        "                                 <div ",
        "                                     onClick={() => setShowIglesias(true)}",
        "                                     className=\"glass-panel gaudi-curves hover-lift animate-fade-in\" ",
        "                                     style={{ ",
        "                                         background: 'linear-gradient(135deg, #451a03 0%, #7d201c 100%)', ",
        "                                         padding: isMobile ? '1.5rem' : '2.5rem', ",
        "                                         borderRadius: '35px', ",
        "                                         cursor: 'pointer',",
        "                                         border: '1px solid rgba(245,158,11,0.4)',",
        "                                         position: 'relative',",
        "                                         overflow: 'hidden',",
        "                                         display: 'flex',",
        "                                         flexDirection: 'column',",
        "                                         boxShadow: '0 20px 40px rgba(0,0,0,0.5)'",
        "                                     }}",
        "                                 >",
        "                                     <div style={{ position: 'absolute', top: '-5%', right: '-5%', opacity: 0.1, zIndex: 0 }}>",
        "                                         <Church size={isMobile ? 150 : 220} color=\"#f59e0b\" />",
        "                                     </div>",
        "                                     <div style={{ position: 'relative', zIndex: 1, height: '100%', display: 'flex', flexDirection: 'column' }}>",
        "                                         <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>",
        "                                             <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>",
        "                                                 <span style={{ background: '#f59e0b', color: '#000', padding: '0.4rem 1.2rem', borderRadius: '50px', fontSize: '0.7rem', fontWeight: 900 }}>PATRIMONIO VLS</span>",
        "                                             </div>",
        "                                             <div style={{ display: 'flex', gap: '8px', color: '#f59e0b', opacity: 1 }}>",
        "                                                 <HistoryIcon size={18} className=\"animate-pulse\" />",
        "                                             </div>",
        "                                         </div>",
        "                                         <h2 style={{ color: 'white', fontSize: isMobile ? '1.5rem' : '1.8rem', fontWeight: 900, lineHeight: 1.1, marginBottom: '1rem', fontFamily: '\"Outfit\", sans-serif' }}>IGLESIAS DE PIEDRA</h2>",
        "                                         <p style={{ color: 'rgba(255,255,255,0.9)', fontSize: '0.95rem', margin: '0 0 1.5rem 0', fontWeight: 400, lineHeight: 1.4, flex: 1 }}>",
        "                                             Investigación: Los secretos de La Merced y la arquitectura de piedra caliza que define el alma de La Serena Colonial.",
        "                                         </p>",
        "                                         <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto' }}>",
        "                                             <button className=\"btn-vls-action-light\" style={{ padding: '0.6rem 1.5rem', fontSize: '0.8rem', background: '#f59e0b', color: '#000', border: 'none', borderRadius: '12px', fontWeight: '900' }}>EXPLORAR RUTA</button>",
        "                                             <span style={{ color: '#f59e0b', fontWeight: 'bold', fontSize: '0.7rem', letterSpacing: '1px' }}>VLS PATRIMONIAL</span>",
        "                                         </div>",
        "                                     </div>",
        "                                 </div>",
        "                             </div>",
        "                        </div>"
    ];
    
    lines.splice(startIndex, endIndex - startIndex, ...cleanBlock);
    fs.writeFileSync(path, lines.join('\n'), 'utf8');
    console.log('Successfully repaired HubDashboard.jsx (Premium Card Balanced)');
} else {
    console.error('Markers not found', { startIndex, endIndex });
}
