import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    es: {
        welcome: "¡Bienvenido a Smart Comuna!",
        back: "Volver",
        search: "Buscar...",
        loading: "Procesando...",
        today: "HOY",
        tomorrow: "MAÑANA",
        days_left: "QUEDAN {n} DÍAS",
        settings: "Ajustes",
        profile: "Perfil",
        logout: "Cerrar Sesión",
        urgent: "URGENTE",
        critical: "CRÍTICO",
        high: "ALTO",
        mid: "MEDIO",
        saludTitle: "Smart Salud (Hub)",
        saludSub: "Reserva Horas y Seguros Comunitarios",
        citizensTitle: "Smart Citizens",
        citizensSub: "Gestión Vecinal y Reportes",
        kioskoTitle: "Kiosko de Diarios",
        kioskoSub: "Prensa Regional y Nacional",
        airportTitle: "Aeropuerto La Florida",
        airportSub: "Vuelos y Radar 3D",
        visionTitle: "Vecinojos (Cámaras)",
        visionSub: "Monitoreo Colaborativo",
        broadcasterTitle: "Broadcast Studio",
        broadcasterSub: "Producción de Radio y TV",
        memorialTitle: "Hijos de la Región",
        memorialSub: "Memorial Digital",
        auditoriaTitle: "Auditoría Vecinal",
        auditoriaSub: "Transparencia y KPI",
        parlamentoTitle: "Parlamento del Ecosistema",
        parlamentoSub: "Votaciones y Diálogo",
        gymTitle: "Gimnasio 3D",
        gymSub: "Deporte con Serenito",
        motorTitle: "Motor del Tiempo",
        motorSub: "Archivo Histórico X",
        adminTitle: "Smart Administration",
        adminSub: "Gestión Interna y RRHH",
        radioTitle: "VLS Radio Master",
        radioSub: "Señales y Noticias",
        glosarioTitle: "Consultas & Glosario",
        glosarioSub: "Diccionario Institucional"
    },
    en: {
        welcome: "Welcome to Smart Comuna!",
        back: "Back",
        search: "Search...",
        loading: "Processing...",
        today: "TODAY",
        tomorrow: "TOMORROW",
        days_left: "{n} DAYS LEFT",
        settings: "Settings",
        profile: "Profile",
        logout: "Logout",
        urgent: "URGENT",
        critical: "CRITICAL",
        high: "HIGH",
        mid: "MEDIUM",
        saludTitle: "Smart Health Hub",
        saludSub: "Health Appointments & Insurance",
        citizensTitle: "Smart Citizens",
        citizensSub: "Community Management & Reports",
        kioskoTitle: "News Stand",
        kioskoSub: "Regional & National Press",
        airportTitle: "La Florida Airport",
        airportSub: "Flights & 3D Radar",
        visionTitle: "Vecinojos (Cameras)",
        visionSub: "Collaborative Monitoring",
        broadcasterTitle: "Broadcast Studio",
        broadcasterSub: "Radio & TV Production",
        memorialTitle: "Region's Children",
        memorialSub: "Digital Memorial",
        auditoriaTitle: "Citizen Audit",
        auditoriaSub: "Transparency & KPI",
        parlamentoTitle: "Ecosystem Parliament",
        parlamentoSub: "Voting & Dialogue",
        gymTitle: "3D Gym",
        gymSub: "Sport with Serenito",
        motorTitle: "Time Engine",
        motorSub: "Historical Archive X",
        adminTitle: "Smart Administration",
        adminSub: "Internal Management & HR",
        radioTitle: "VLS Radio Master",
        radioSub: "Signals & News",
        glosarioTitle: "Queries & Glossary",
        glosarySub: "Institutional Dictionary"
    },
    zh: {
        welcome: "欢迎来到智慧社区！",
        back: "返回",
        search: "搜索...",
        loading: "处理中...",
        today: "今天",
        tomorrow: "明天",
        days_left: "剩余 {n} 天",
        settings: "设置",
        profile: "个人资料",
        logout: "退出登录",
        urgent: "紧急",
        critical: "关键",
        high: "高",
        mid: "中",
        saludTitle: "智慧健康中心",
        saludSub: "预约掛号与社区保险",
        citizensTitle: "智慧公民",
        citizensSub: "邻里管理与报告",
        kioskoTitle: "报刊亭",
        kioskoSub: "地区与国家新闻",
        airportTitle: "拉弗洛里达机场",
        airportSub: "航班与 3D 雷达",
        visionTitle: "邻里之眼 (摄像头)",
        visionSub: "协作监控",
        broadcasterTitle: "广播工作室",
        broadcasterSub: "广播与电视制作",
        memorialTitle: "地区之子",
        memorialSub: "数字纪念碑",
        auditoriaTitle: "公民审计",
        auditoriaSub: "透明度与 KPI",
        parlamentoTitle: "生态议会",
        parlamentoSub: "投票与对话",
        gymTitle: "3D 健身房",
        gymSub: "与 Serenito 运动",
        motorTitle: "时间引擎",
        motorSub: "历史档案 X",
        adminTitle: "智慧管理",
        adminSub: "内部管理与人力资源",
        radioTitle: "VLS 广播大师",
        radioSub: "信号与新闻",
        glosarioTitle: "查询与词汇表",
        glosarioSub: "机构词典"
    },
    arn: {
        welcome: "¡Küme Akun Smart Comuna mew!",
        back: "Wiñotun",
        search: "Kintun...",
        loading: "Küzawün...",
        today: "FACHANTÜ",
        tomorrow: "WÜLLE",
        days_left: "PETU {n} ANTÜ",
        settings: "Zugu",
        profile: "Wall",
        logout: "Tripay",
        urgent: "ZUGU",
        critical: "NEWEN",
        high: "FÜTRA",
        mid: "RAGI",
        saludTitle: "Smart Mongen Hub",
        saludSub: "Kellun ka Mongen",
        citizensTitle: "Smart Lof",
        citizensSub: "Küzaw ka Wirin",
        kioskoTitle: "Chilkatuwe",
        kioskoSub: "Nütram ka Wirin",
        glosarioTitle: "Zun",
        glosarioSub: "Mapu Chilkatuwe"
    },
    it: {
        welcome: "Benvenuti in Smart Comuna!",
        back: "Indietro",
        search: "Cerca...",
        loading: "In corso...",
        today: "OGGI",
        tomorrow: "DOMANI",
        days_left: "MANCANO {n} GIORNI",
        settings: "Impostazioni",
        profile: "Profilo",
        logout: "Disconnetti",
        urgent: "URGENTE",
        critical: "CRITICO",
        high: "ALTO",
        mid: "MEDIO",
        saludTitle: "Smart Salute Hub",
        saludSub: "Appuntamenti e Assicurazioni",
        citizensTitle: "Smart Citizens",
        citizensSub: "Gestione e Rapporti",
        adminTitle: "Smart Administration",
        adminSub: "Gestione Interna e Risorse Umane",
        radioTitle: "VLS Radio Master",
        radioSub: "Segnali e Notizie"
    },
    fr: {
        welcome: "Bienvenue à Smart Comuna!",
        back: "Retour",
        search: "Chercher...",
        loading: "Traitement...",
        today: "AUJOURD'HUI",
        tomorrow: "DEMAIN",
        days_left: "IL RESTE {n} JOURS",
        settings: "Paramètres",
        profile: "Profil",
        logout: "Déconnexion",
        urgent: "URGENT",
        critical: "CRITIQUE",
        high: "HAUT",
        mid: "MOYEN",
        saludTitle: "Smart Santé Hub",
        saludSub: "Rendez-vous et Assurance",
        citizensTitle: "Smart Citizens",
        citizensSub: "Gestion et Rapports",
        adminTitle: "Smart Administration",
        adminSub: "Gestion Interne et RH",
        radioTitle: "VLS Radio Master",
        radioSub: "Signaux et Nouvelles"
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('vls_lang') || 'es');

    const t = (key, params = {}) => {
        let text = translations[lang]?.[key] || translations['es']?.[key] || key;
        Object.keys(params).forEach(p => {
            text = text.replace(`{${p}}`, params[p]);
        });
        return text;
    };

    useEffect(() => {
        localStorage.setItem('vls_lang', lang);
        // Force update for non-context components if needed
        window.dispatchEvent(new CustomEvent('lang-changed', { detail: lang }));
    }, [lang]);

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => useContext(LanguageContext);
